#!/bin/bash

alias ll='ls -alF'

if [[ -z $ZCLASSIC_DATA_DIR ]]
then
    export ZCLASSIC_DATA_DIR=~/.zclassic
fi
if ! [[ -d $ZCLASSIC_DATA_DIR ]]
then
    mkdir -p $ZCLASSIC_DATA_DIR
    chmod 777 $ZCLASSIC_DATA_DIR
fi
if [[ -z "$WALLET_DIR" ]]
then
    export WALLET_DIR=~/share
fi
if ! [[ -d "$WALLET_DIR" ]]
then
    mkdir -p "$WALLET_DIR"
    chmod 777 "$WALLET_DIR"
fi

###################
# ZClassic aliases
###################

alias zcl-help='cat %CMDS_DIR%/zclassic-cmds-help'

alias zcl-balance='echo "Total balance:" && '\
'zcash-cli ${ZCASHCLI_PARAMS} z_gettotalbalance'\

alias zcl-listunspent='echo "Unspent (public coins):" && zcash-cli ${ZCASHCLI_PARAMS} listunspent'

alias zcl-send='%CMDS_DIR%/send.sh'

alias zcl-backup='%CMDS_DIR%/backup_wallet.sh'
alias zcl-backup='%CMDS_DIR%/restore_wallet.sh'

alias zcl-showwallet='zcl-exportwallet && '\
'cat ${WALLET_DIR}/wallet.txt'

alias zcl-transactions='zcash-cli ${ZCASHCLI_PARAMS} listtransactions'

alias zcl-transaction='zcash-cli ${ZCASHCLI_PARAMS} gettransaction'

alias zcl-listaddrs='echo "Anonymous addresses:" && '\
'zcash-cli ${ZCASHCLI_PARAMS} z_listaddresses && '\
'echo "Received by addresses:" && '\
'zcash-cli ${ZCASHCLI_PARAMS} listreceivedbyaddress 0 true'

alias zcl-status='zcl-listaddrs && '\
'echo && '\
'zcl-balance && '\
'echo && '\
'echo "Blockchain info:" && '\
'zcash-cli ${ZCASHCLI_PARAMS} getinfo'
 
alias zcl-newaddr='zcash-cli ${ZCASHCLI_PARAMS} getnewaddress'

alias zcl-newzaddr='zcash-cli ${ZCASHCLI_PARAMS} z_getnewaddress'

alias zcl-send='%CMDS_DIR%/send.sh'

alias zcl-config='cat ${ZCLASSIC_DATA_DIR}/zclassic.conf'

alias zcl-connections='zcash-cli ${ZCASHCLI_PARAMS} getpeerinfo'

alias zcl-operations='echo "Operations status:" && '\
'zcash-cli ${ZCASHCLI_PARAMS} z_getoperationstatus'

alias zcl-logs='tail -20 ${ZCLASSIC_DATA_DIR}/debug.log'

alias zcl-stop='zcash-cli ${ZCASHCLI_PARAMS} stop'
